version: 2
build:
  os: ubuntu-22.04

  tools:
    python: "3.11"
    rust: "latest"

  apt_packages:
    - libpango1.0-dev
    - graphviz

  jobs:
    post_checkout:
      - git submodule update --init --recursive

    post_install:
      - cd manim-forge
      - maturin develop --release
      - cd ..

python:
   install:
      - requirements: docs/rtd-requirements.txt
      - requirements: docs/requirements.txt
      - method: pip
        path: .
